Repository nextcloud-libraries/nextcloud-l10n, pull requests merged in 2023-01, with the labels that each got.

#542 Provide all translation related functions
  lib/date.ts
  lib/index.ts
  lib/registry.ts
  lib/translation.ts
  package-lock.json
  package.json
  test/index.test.js
Labels: enhancement, technical debt

#360 Update npm and node engines versions
  package.json
Labels: dependencies

#547 Fix "build status" badge in README.mde
  README.md
Labels: bug

#546 Fix building and deploying documentaton
  .github/workflows/documentation.yml
  lib/gettext.ts
  lib/index.ts
  lib/translation.ts
  package-lock.json
  package.json
  typedoc.json
Labels: bug, documentation

#551 Add missing test cases for `gettext.ts`
  tests/gettext.test.js
Labels: enhancement

#552 Add missing test cases for `date.ts`
  package-lock.json
  package.json
  tests/date.test.ts
  tests/index.test.js
Labels: enhancement

#554 Enforce nextcloud code style | Adding eslint linting
  .eslintrc.json
  .github/workflows/lint-eslint.yml
  jest.config.js
  lib/date.ts
  lib/gettext.ts
  lib/index.ts
  lib/registry.ts
  lib/translation.ts
  package-lock.json
  package.json
  rollup.config.mjs
  tests/date.test.ts
  tests/gettext.test.js
  tests/index.test.js
Labels: enhancement

#555 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#563 fix(config): fix npmignore config
  .npmignore
Labels: bug

#562 fix(config): fix tsconfig out dir typings
  rollup.config.mjs
  tsconfig.json
Labels: bug

#556 Fix standalone registeration
  lib/registry.ts
  tests/index.test.js
Labels: bug

#565 Add more tests for `registry.ts` and fix typings
  lib/registry.ts
  lib/translation.ts
  package.json
  tests/registry.test.ts
Labels: enhancement

#566 Add missing documentation
  lib/index.ts
  lib/registry.ts
Labels: documentation

#569 fix: Remove dead code from previous server implementation
  lib/translation.ts
Labels: enhancement

#572 Remove warning "No translation for appId "${appId}" have been registered"
  lib/registry.ts
  tests/gettext.test.js
  tests/registry.test.ts
Labels: bug

#573 feat(tests): Add some basic tests for `getPlural`
  tests/translation.test.ts
Labels: enhancement

#571 Fix loading translations and add test cases
  lib/translation.ts
  package-lock.json
  package.json
  tests/loadTranslations.test.ts
Labels: bug
