Repository nextcloud-libraries/nextcloud-l10n, pull requests merged in 2023-06, with the labels that each got.

#627 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review

#633 fix: Add the typings to the package exports
  package.json
Labels: bug, 3. to review

#638 chore: update node engines to next LTS
  package.json
Labels: dependencies, automated, 3. to review

#634 chore: Bump dependencies in `package.json`
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: 3. to review

#640 fix: Update exported `NextcloudWindowWithRegistry` type
  lib/date.ts
  lib/registry.ts
Labels: 3. to review

#639 feat: Add new `isRTL` function
  lib/index.ts
  lib/locale.ts
  lib/translation.ts
  tests/locale.test.ts
  tests/translation.test.ts
Labels: enhancement, 3. to review

#642 feat: add node testing workflow
  .github/workflows/node-test.yml
  package.json
Labels: 3. to review

#643 Prepare new release: v2.2.0
  .npmignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#644 fix(loadTranslations): Handle edge cases
  lib/translation.ts
  tests/loadTranslations.test.ts
Labels: 3. to review

#645 chore: Adjust changelog for 2.2.0 release
  CHANGELOG.md
Labels: 3. to review
