Repository nextcloud-libraries/nextcloud-l10n, pull requests merged in 2025-02, with the labels that each got.

#847 ci: Update workflows from organization
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
Labels: 3. to review, type: CI

#846 doc: replace missing exports plugin to also document internal types
  lib/date.ts
  lib/gettext.ts
  lib/index.ts
  lib/locale.ts
  lib/registry.ts
  lib/translation.ts
  package-lock.json
  package.json
  typedoc.json
Labels: type: documentation, 3. to review

#850 feat(gettext): Add `detectLanguage` method and deprecate `detectLocale`
  CHANGELOG.md
  lib/gettext.ts
Labels: type: enhancement, 3. to review

#852 chore: Add missing trailing comma in vite config
  vite.config.ts
Labels: 3. to review, type: refactor

#853 doc: Clarify readme about Nextcloud provided and custom translations
  README.md
Labels: type: documentation, 3. to review

#855 fix(isRTL): Correctly handle Urdu and Uzbek Afghan
  lib/locale.ts
  tests/locale.test.ts
Labels: type: bug, 3. to review

#854 feat: Overload translate function to either allow number or placeholder as third arg
  lib/translation.ts
  tests/translation.test.ts
Labels: type: enhancement, 3. to review

#851 refactor(gettext): Drop `node-gettext` dependency and use our translation logic
  .eslintrc.json
  lib/gettext.ts
  lib/registry.ts
  lib/translation.ts
  package-lock.json
  package.json
  tests/gettext.test.ts
  tests/translation.test.ts
  tsconfig.json
Labels: type: dependencies, 3. to review, type: refactor

#784 docs: improve return type of getFirstDay()
  .eslintrc.json
  lib/date.ts
Labels: type: documentation, 3. to review

#860 fix(registry): Prevent prototype polluting
  lib/registry.ts
Labels: type: bug, 3. to review

#859 chore: Prepare v3.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
