Repository nextcloud-libraries/nextcloud-l10n, pull requests merged in 2025-05, with the labels that each got.

#921 feat: add method to format relative time
  lib/index.ts
  lib/time.ts
  tests/time.test.ts
Labels: type: enhancement, 3. to review

#927 fix(translations): use language instead of locale + refactor the `loadTranslations` method
  CHANGELOG.md
  lib/translation.ts
  package-lock.json
  package.json
  tests/loadTranslations.test.ts
Labels: type: bug, 3. to review

#928 refactor: simplify `loadTranslations`
  lib/translation.ts
Labels: 3. to review, type: refactor

#864 fix(locale): fallback to device preferences instead of 'en'
  lib/locale.ts
  package.json
  tests/locale.test.ts
Labels: type: bug, 3. to review
